### ISSUE TITLE
신성솔라에너지 증평 - 모드버스 통신 불량 건 외 1

### ISSUE THREAD

**Issue by shpark2** [reti-devops/CBL#2]
[장소] 신성솔라에너지 증평 공장
[시간] 2016.05.17 오전 10시 30분부터 ~
[현상]
1. ping 응답이 있지만 모드 버스 통신이 되지 않았고, 현장에서 확인해보니 LCD가 부팅 중간에 멈춰 있었습니다.
2. 전력 측정 데이터가 한 달 누적이 안되고 중간에 초기화 하는 현상
[재현 경로]
1. 부팅 중간에 통신에 문제가 생기면 발생할 수 있습니다. 다만, 현장에서는 재현하지 못했습니다.
2. 현장에서 바로 재현하지 못하고 시간이 지나봐야 알 수 있다고 판단했습니다.
[대처]
1번 문제의 경우 결국 기존 워치독 시나리오의 문제인 것으로 판단하였으며, 펌웨어와 LCD 프로그램 업데이트가 예정되어 있었기에 CBL, CBE 펌웨어 업그레이드, LCD 프로그램 업데이트를 하였습니다. 모든 업데이트 후 관제실에서 DS-125 manager 로 통신 확인하였으며, 코에버 정보통신의 프로그램으로도 제대로 통신이 되는지 확인하였으며, 각각 둘 다 이상 없었습니다.

2번 문제의 경우 업데이트를 하면서 나아졌을 것이라 생각하며 보다 정확한 것은 시간이 지나봐야 알 수 있을 것이라 생각합니다.

**Comment by wizdear** [comment]
1번 현상의 원인은 control board가 LCD의 전원제어를 제대로 못한 경우에 발생합니다. 과거는 LCD 전원제어를 위해 chip reset이용했는데, 이 경우 LCD가 완전히 꺼지지 않아 memory 회수에 문제가 있었던 것 같습니다. 최근 버전의 control board는 이를 개선하여 전원제어시에 LCD의 전원을 완전히 내립니다. 
2번 현상은 현재 LCD 버전에서 해결되었습니다.
