### ISSUE TITLE
SH-BP 부평 - 네트워크 불량 외 1건

### ISSUE THREAD

**Issue by shpark2** [reti-devops/CBL#3]
[장소] SHBP (부평)
[시간] 2016.05.18 오전 10시 30분부터 ~
 [현상]
1. ip 주소가 맞지 않아서 정상적 통신이 되지 않는 현상
2. LCD 연결 케이블 단선 현상
3. 그룹 매핑 오류
[재현 경로]
1. 잘못 입력된 ip 주소로 인한 네트워크 통신 불량으로 재현 가능합니다.
2. LCD 연결 케이블 중 몰렉스 핀으로 된 부분이 빠져있어 이 부분은 강한 힘으로 잡아 당기면 재현 가능합니다.
3. master/slave 설정 충돌시 재현 가능합니다.
 [대처]
1번 문제의 경우 처음에 ip 주소를 입력을 해도 재시작을 하고나면 다른 ip 주소가 설정 되어 있었는데 이는 DHCP 설정이 체크가 되어 있어서 그런 것으로 체크를 해제하는 것으로 해결 했습니다. 

다만, 중간에 LCD에 문제가 생긴것으로 판단되어 LCD를 교체를 하였고, LCD교체 후 사용하던 SD 카드를 꽂아 넣어 내부 DB가 꼬여 No data 현상이 발생되었으며, SD카드 내부의 DB를 초기화 하여 다시 실행하니 정상 작동하였습니다.

2번 문제의 경우 준비하여 가져간 새로운 케이블로 교체 후 정상 작동 하였습니다.

3번 문제의 경우 충돌난 그룹을 찾아 cap을 벗겨보니 slave-slave-slave-master 순서여야 하지만
모듈 한 개의 스위치가 잘못되어 master-slaver-slave-master 로 되어 있었습니다. 그래서 다시 스위치를 slave로 바꾼 후 설정을 하니 정상작동 하였습니다.

공장 내부 LCD 기준 6개 모두 모듈, CBL 펌웨어 업그레이드와 LCD 프로그램 업그레이드를 하였습니다.

**Comment by wizdear** [comment]
Lable과 Assignee를 표시해주세요. 
모든 문제가 해결되었으므로, close합니다.
